name : 'Terraform Github Action'
on :
    push:
        branches: 
            - master
jobs :
    terraform :
        name: 'Terraform'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout'
              uses: actions/checkout@master

            - name: 'setup terraform'
              uses: hashicorp/setup-terraform@v1
            
            - run: terraform init
            - run: terraform apply -y
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}